/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Client */

#ifndef _Included_Client
#define _Included_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Client
 * Method:    print
 * Signature: ()V
 */
    JNIEXPORT void JNICALL Java_Client_print(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
